name: ci ğŸš€

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code ğŸ“¥
      - name: install pnpm ğŸ“¦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "pnpm"
      - name: install dependencies ğŸ”§
        run: pnpm install
      - name: run check âœ…
        run: pnpm check

  create-plainweb:
    runs-on: ubuntu-latest
    steps:
      - name: install pnpm ğŸ“¦
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: setup node ğŸŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - name: create plainweb project ğŸª¨
        run: |
          pnpm dlx create-plainweb@latest my-plainweb-project --yes --no-git-init --debug
        env:
          npm_config_user_agent: ${{ github.actor }}
      - name: run build, test, and check ğŸš€
        run: |
          cd my-plainweb-project
          pnpm build
          pnpm test
          pnpm check
      - name: start server and check response ğŸŒ
        run: |
          cd my-plainweb-project
          pnpm start &
          sleep 5  # Wait for the server to start
          if curl -s http://localhost:3000 | grep -q "Let's go"; then
            echo "Server started successfully and contains 'Let's go'"
          else
            echo "Server check failed"
            exit 1
          fi
          kill $!  # Stop the server
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy to fly cli ğŸš€
        run: |
          cd my-plainweb-project
          sed -i 's/app = '"'"'my-app'"'"'/app = '"'"'plainweb-template'"'"'/' fly.toml
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: check fly deployment â¬†ï¸
        run: curl -s http://plainweb-template.fly.dev | grep -q "Let's go"
